apiVersion: v1
kind: Service
metadata:
  name: lms-service
  namespace: deejoft-lms
  labels:
    app: lms
spec:
  selector:
    app: lms
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  type: NodePort